# Directory
log_dir: /logs
output_dir: /outputs
save_dir: /models
wandb_dir: /wandb

# Weights & Biases
project_name: "phasic-exploration--dcpg"
# model_name: "PPO + Explore-GO"
model_name: "PPO"

# Experiment
log_interval: 10
num_eval_episodes: 4

# Environment
num_env_steps: 5.e+4

# Rollout
num_processes: 4
num_steps: 10

# Policy gradient
gamma: 0.9
gae_lambda: 0.95

# Actor-critic
actor_critic_class: IllustrativeModel
actor_critic_params:
  shared: False

# Pure Exploration
# num_pure_expl_steps: 4
num_pure_expl_steps: 0

# Agent
agent_class: PPO
agent_params:
  # PPO params
  clip_param: 0.2
  ppo_epoch: 3
  num_mini_batch: 8
  value_loss_coef: 0.5
  entropy_coef: 0.01
  lr: 1.0e-4
  eps: 1.0e-5
  max_grad_norm: 0.5
